.TH cudf2lp 1 "September 19, 2017"  "Version 1.9.4" "USER COMMANDS"
.SH NAME
cudf2lp \- a preprocessor for CUDF documents

.SH SYNOPSIS
\fBcudf2lp\fR [\fIOPTION\fR]... [\fIFILE\fR]

.SH DESCRIPTION
.B cudf2lp
simplifies a given CUDF specification and converts it into a set of facts suitable to be processed with an ASP grounder and solver
- e.g., \&\fIgringo\fR\|(1) and \&\fIclasp\fR\|(1).
It is intended to be called by \&\fIaspcud\fR\|(1), but may also be used independently.

It reads from the given \fRFILE\fR or from standard input if ommited.

.SH OPTIONS
.B cudf2lp
supports the following options:

.TP
\fB\-h\fR, \fB\-\-help\fR
print help text
.TP
\fB\-v\fR, \fB\-\-version\fR
print version and license information
.TP
\fB\-V\fR, \fB\-\-verbose\fR[=\fIN\fR]
set the verbosity level to \fIN\fR or the maximum if omitted
.TP
\fB\-c\fR \fICRITS\fR, \fB\-\-criterion\fR=\fICRITS\fR
preprocess for specific optimization criteria (defaults to none):
  \fICRITS\fR: none | paranoid | trendy | \fICRIT\fR\\(','\fICRIT\fR\\)*
  \fICRIT\fR : \fISIGN\fR count(\fISET\fR) | 
       | \fISIGN\fR sum(\fISET\fR,\fIATTR\fR) 
       | \fISIGN\fR unsat_recommends(\fISET\fR)
       | \fISIGN\fR aligned(\fISET\fR,\fIATTR\fR,\fIATTR\fR) 
       | \fISIGN\fR notuptodate(\fISET\fR)
  \fISIGN\fR : '+' | '-'
  \fIATTR\fR : CUDF attribute name
  \fISET\fR  : solution | changed | new | removed | up | down
       | installrequest | upgraderequest | request

for backwards compatibility, the following aliases can be used:
  new              = count(new)
  removed          = count(removed)
  changed          = count(changed)
  notuptodate      = notuptodate(solution)
  unsat_recommends = unsat_recommends(solution)
  sum(name)        = sum(name,solution)
.TP
\fB\-\-addall\fR
disable preprocessing and add all packages

.SH AUTHOR
.B cudf2lp
has been written by Roland Kaminski.

.SH SEE ALSO
\&\fIaspcud\fR\|(1), \&\fIgringo\fR\|(1), \&\fIclasp\fR\|(1),
and <http://www.mancoosi.org/cudf/> for the specification of the CUDF format.
