set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_C_COMPILER mingw32-gcc)
set(CMAKE_CXX_COMPILER mingw32-g++)

SET(CMAKE_FIND_ROOT_PATH /usr/mingw32 $ENV{HOME}/local/mingw32)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
